FROM microsoft/dotnet:2.1-sdk AS build

COPY build_nuget_package.sh /build_scripts/

WORKDIR /app_src

ENTRYPOINT ["/bin/bash", "/build_scripts/build_nuget_package.sh", "--outputDir=/output", "--testResultsDir=/test-results"]